# Ros ile controller manager'ın etkileşimi geçereken, yapılandırma parametrelerini ayarladığımız dosyadır !!
controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: True

    diff_drive_robot_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
diff_drive_robot_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    left_wheel_names: ["rear_left_wheel_joint"]
    right_wheel_names: ["rear_right_wheel_joint"]

    publish_rate: 50.0
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    wheel_separation: 0.5
    wheel_radius: 0.1

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    cmd_vel_timeout: 0.5
    base_frame_id: base_footprint
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -0.5
        has_acceleration_limits: true
        max_acceleration: 0.8
        min_acceleration: -0.4
        has_jerk_limits: false
        max_jerk: 5.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.7
        has_acceleration_limits: true
        max_acceleration: 1.5
        has_jerk_limits: false
        max_jerk: 2.5 
